name: "Tin\u2013Zinc\u2013Nickel | EU27\u2013China\u2013RoW | Coupled SD\u2013dMFA\
  \ (loose iterative | mvp)"
extends: ./_core.yml
includes:
  scenarios: ../scenarios/mvp/*.yml
strategy:
  refinery_stockpile_release_rate: 0.15
